title: Owieczka 
description: Owieczka description
theme: just-the-docs

url: https://owieczka.github.io

logo: "/assets/images/OwieczkaChod2.gif"


mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
