title: Owieczka 
description: Owieczka description
theme: just-the-docs
#remote_theme: just-the-docs/just-the-docs@v0.5.2
#repository: "pdmosses/test-nav"

url: https://owieczka.github.io

logo: "/assets/images/OwieczkaChod2.gif"

mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } }, tex2jax: { inlineMath: [['$','$']] } })'

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

compress_html:
  blanklines: true